# Site settings
title: Aitan Yerassilov
twitter_username: yerassil
name: Aitan Yerassilov

# Build settings
markdown: markdown

#User specific content
#Links that will appear in the navbar
primarylinks:


#Any buzzword skills you want to include
skills:
 - Python
 - Django
 - Django REST framework
 - SQL
 - Git
 - Vue.js
 

#Work experience is required
roles:
 - title: Senior Account Executive
   start: 2012
   end: 2019
   employer: Aon Kazakhstan Insurance Broker
   description: Leading insurance broker offering wide range of insurance broking services for both multinational and local companies operating in Kazakhstan.
 - title: Senior Manager
   start: 2009
   end: 2012
   employer: Kazkommerts-Policy Insurance Company
   description: 

#Education is required
education:
 - level: Certificate of completion
   date: 2019
   subject: Python, Django
   school: Vault77 Programming School, Almaty
 - level: Certificate of completion
   date: 2018
   subject: Web intensive, Python, Django
   school: Method Programming School, Almaty
 - level: Bachelor of Science candidate
   date: 2009
   subject: Biotechnology
   school: Indiana University Bloomington



#List of interesting Github repo/projects to include - optional
github:
 - Yerassil/django_tickets
 - Yerassil/django_bookmarks
 - Yerassil/django_social
 - Yerassil/cat_a_day_bot
 - Yerassil/django_one


intro: |
  Self-motivated developer with stack focused primarily on Python and Django framework seeking entry level web developer position in a growing company with strong team of IT-professionals to implement hard and soft skills gained from completed courses and self-education.
  Able to communicate effectively in a team setting and have strong willingness to learn new technologies that may be required in production. 

